// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/blog/:action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/[action].post').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/comments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comments.post').default>>>>
    }
    '/api/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.get').default>>>>
    }
    '/api/friend-links': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friend-links.get').default>>>>
    }
    '/api/likes': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/likes.post').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts.get').default>>>>
    }
    '/api/posts/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[slug].get').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.get').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags.get').default>>>>
    }
    '/rss.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/rss.xml').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}