// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/26 12:22:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/czj/Desktop/新建文件夹/blog-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/plugins/**/*.{js,ts,mjs}","C:/Users/czj/Desktop/新建文件夹/blog-site/composables/**/*.{js,ts,mjs}","C:/Users/czj/Desktop/新建文件夹/blog-site/utils/**/*.{js,ts,mjs}","C:/Users/czj/Desktop/新建文件夹/blog-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/czj/Desktop/新建文件夹/blog-site/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;